### ISSUE TITLE
API needs /reset

### ISSUE THREAD

**Issue by JacobAMason** [ejzavala00/Carnivore-Cruise-Lines#10]
We are beginning the process of placing orders to the various endpoints. We can successfully place orders to your API, but there is no `/reset` endpoint by which we can reset the state of the database so we can test.

**Comment by jcw931** [comment]
Gotcha. Need that tonight? and We have the update availability for actual use but didn't think to add a reset for testing.

**Comment by JacobAMason** [comment]
I see what you're referring to so we'll try to get that to work. It's not urgent.

**Comment by jcw931** [comment]
We can use it with the web front using cURL.  Should work with swaggerhub too.

**Comment by JacobAMason** [comment]
Yeah we use postman to do most of that sort of stuff

**Comment by jcw931** [comment]
Are you using our /system/history endpoint? I updated swaggerhub for our patch tomorrow (haven't published yet). Was going to add the /reset to the swaggerhub and just publish the new one. but if you are using it I will wait so that it doesn't break that too

**Comment by JacobAMason** [comment]
No. We are actually keeping track of purchase history ourselves as well and depend upon our own endpoints for that.

**Comment by jcw931** [comment]
Reset is up should be working I quickly tested it.

**Comment by JacobAMason** [comment]
lgtm
