### ISSUE TITLE
Incorrect return code

### ISSUE THREAD

**Issue by JacobAMason** [ejzavala00/Carnivore-Cruise-Lines#11]
On this endpoint https://app.swaggerhub.com/apis/Carnivore-Cruises/Carnivore_Cruise_Lines/1.3.4#/developers/select_item the "item could not be selected" repsonse code is 400, which is correct, but the implementation is returning 200, which makes the client believe the request has succeeded, even though the message says that it failed.

No rush on this one.

**Comment by jcw931** [comment]
Not to sound too dumb here but.... how can I get my "return jsonify(status="xxx")" to code 400. return the value 400? thought there would be a keyword status_code or something

**Comment by JacobAMason** [comment]
You should be able to do `return jsonify(status="..."), 400`

**Comment by jcw931** [comment]
Yes, sorry I found that right after I ask. Should he told you I found it.

**Comment by JacobAMason** [comment]
Ha, it's all good

**Comment by jcw931** [comment]
You guys should be good to go on the error codes now

**Comment by JacobAMason** [comment]
lgtm
