### ISSUE TITLE
API fix request

### ISSUE THREAD

**Issue by JacobAMason** [ejzavala00/Carnivore-Cruise-Lines#4]
The endpoint at Line 110 "/inventory/location/{State}/{City}:" should use lowercase path variables. There is a bizarre bug in swagger-codegen that incorrectly handles uppercase names.

The put request on line 99 doesn't include the path variable "itemID" in the parameters list. A bug in the swagger ui is causing this error to slip through.

Please reversion to 1.1.2, if no other changes have been make, otherwise reversion as you see fit.

**Comment by JacobAMason** [comment]
Can you change the '/inventory/location' endpoint to accept state and city as defined in the spec? I somehow was oblivious to this when I first reviewed the endpoint. Locations should be a string of "City, ST"

**Comment by jcw931** [comment]
I can. I just thought you needed it returned in that form.

**Comment by JacobAMason** [comment]
Yeah, that's my bad for not catching that earlier. I was more worried about getting the API client to compile.

**Comment by JacobAMason** [comment]
Also, the server seems down

**Comment by jcw931** [comment]
I see that. I tried to edit it and its down

**Comment by jcw931** [comment]
lemme do some working with it. was about to push out a new build anyways.

**Comment by jcw931** [comment]
I am home now. Going to try to get back up and going for ya. Sorry we have had so many issues. New to gcloud and not very good with docker yet.

**Comment by jcw931** [comment]
do you mind trying it now?

**Comment by JacobAMason** [comment]
lgtm
