### ISSUE TITLE
API fix request

### ISSUE THREAD

**Issue by JacobAMason** [ejzavala00/Carnivore-Cruise-Lines#5]
- [x] CORS is turned off and should be turned on
 - [x] The CruiseItem model has a misspelled attribute: `avalible` should be `available`

**Comment by ejzavala00** [comment]
We added a pip install flask-cors item in the Dockerfile. hopefully that works for you.
Swagger hub documentation is updated v.1.2.0

**Comment by JacobAMason** [comment]
This isn't all that is necessary to enable CORS. See: https://flask-cors.readthedocs.io/en/latest/

**Comment by ejzavala00** [comment]
OK. Is it working now?

**Comment by JacobAMason** [comment]
It appears to be working now, though I don't see the code change that should fix this.

**Comment by jcw931** [comment]
I added some code to the "Server.py" file. it is the current one in use on the cloud. 
" ** code added ** "
from flask_cors import CORS, cross_origin
CORS(app)

**Comment by JacobAMason** [comment]
Okay. Sounds good. Make sure to push it to this repo though

**Comment by jcw931** [comment]
It should be in it's own branch. Made a clean branch with all the updates made to the API. We added functionality and did some more testing.

**Comment by JacobAMason** [comment]
Neato
