### ISSUE TITLE
CruiseItem model doesn't match implementation

### ISSUE THREAD

**Issue by JacobAMason** [ejzavala00/Carnivore-Cruise-Lines#7]
- [x] The CruiseItem model uses `price` but the actual implementation uses `cost`. Please correct this and check other fields that might differ between the model in swaggerhub and the actual implementation. They must stay in sync.
 - [x] The location endpoint also doesn't return an array. It is returning an object with an array inside it. You should return the array only as your API specifies, or change the API on swaggerhub to match

Both issues are visible here:
http://35.196.221.242/inventory/location/Atlanta,%20GA

**Comment by jcw931** [comment]
I made some changes to swaggerhub. I honestly have never used it until this project. Maybe I understood your issue.

**Comment by JacobAMason** [comment]
You fixed the price/cost discrepancy. The value shouldn't be an integer, though. It should be a float. (Don't send 1000. Send 10.00)
I can elaborate on the second issue:
For the `/inventory/location` endpoint above, instead of returning data that looks like 
```
{
  "InventoryArr": {
    "data": [
      {
           ... CruiseItems,
```
you should be returning data that looks like
```
[
    ... Cruise Items,
```

**Comment by JacobAMason** [comment]
Also, there should be a leading 0 for hours in your string timestamps.
We are getting values like `2018-10-28T5:00:00` and should be getting values only like `2018-10-28T05:00:00`

**Comment by jcw931** [comment]
I didn't write the function for the return. He is gone and won't answer me. You want an array of objects returned?

**Comment by jcw931** [comment]
Not a problem. I thought they were supposed to have the 0. must have slipped by

**Comment by JacobAMason** [comment]
Yes, but fixing the timestamp problem is a higher priority for us. We developed a workaround for the other issue in the meantime.

**Comment by JacobAMason** [comment]
Yes, they should have the 0

**Comment by jcw931** [comment]
I can fix timestamp now.  Lemme edit the db and upload a new one

**Comment by JacobAMason** [comment]
cool

**Comment by JacobAMason** [comment]
Also, this from above
> The value shouldn't be an integer, though. It should be a float. (Don't send 1000. Send 10.00)

**Comment by jcw931** [comment]
Can you guys work with the return for now? I see what he did and he bypassed my object. I should have looked at the code not just that it worked when I added it to my endpoint

**Comment by JacobAMason** [comment]
Yeah, we have a workaround for the array return issue

**Comment by jcw931** [comment]
result = {'data': [dict(zip(tuple (query.keys()) ,i)) for i in query.cursor]} is the line he used this is what you are getting

**Comment by JacobAMason** [comment]
It should be something closer to `result = [dict(zip(tuple (query.keys()) ,i)) for i in query.cursor]`, but there is another name wrapping that. `InventoryArr` shouldn't be there either

**Comment by jcw931** [comment]
I know. I am not sure why he has another array around it

**Comment by JacobAMason** [comment]
Yeah, don't worry about that for now, though. See if you can fix the timestamp and the cost type

**Comment by jcw931** [comment]
I am editing it now

**Comment by jcw931** [comment]
While I am in here. Do you want me to update the dates. They are all 2018 looks like

**Comment by JacobAMason** [comment]
Yeah, that'd be good

**Comment by jcw931** [comment]
Mind checking the new Data

**Comment by JacobAMason** [comment]
Leading 0s and floating point numbers. Looks good.

**Comment by jcw931** [comment]
I will dig into the issue with the code. I cannot promise I will find a fast solution to what is done.

**Comment by JacobAMason** [comment]
Mkay

**Comment by jcw931** [comment]
{
    "inventory": [
        {
            "available": 1,
            "cost": 400.95,
            "cruiseLinerID": "Mexico Adventure",
            "departureDate": "2017-11-24T17:00:00",
            "description": "Lovely port-side suite on the Mexico Adventure Cruise Liner",
            "duration": 4,
            "fromLocation": "Atlanta, GA",
            "itemID": "MexicoAdventure-25",
            "name": "Mexico Adventure",
            "returnDate": "2017-11-28T05:00:00",
            "roomCapacity": 6,
            "roomID": 25
        },


is this format better?

**Comment by JacobAMason** [comment]
If you make the API on swaggerhub match, it will be fine.

**Comment by jcw931** [comment]
I can. Just need to wrap my objects in an "inventory" array?

**Comment by JacobAMason** [comment]
Yes. Technically, you don't have to wrap the array at all if you still want to send the array type.

**Comment by jcw931** [comment]
Can I ask a really dumb question. so you guys are using swaggerhub to interact with the actual API implementation?

**Comment by jcw931** [comment]
I have never worked with SwaggerHub. I was under the impression it was just the documentation

**Comment by JacobAMason** [comment]
swagger created an API spec that can generate clients and servers. If we tried to hand write wrappers for every API, we'd die. Instead, we just autogenerate a typescript client from your swagger yaml. All the APIs from each team live in here https://github.com/sw-arch/Norbitz/tree/master/web-frontend/norbitz/src/apis and the getApi.sh script lets us pass a url to a json version of your swagger yaml and it will create a service we can consume.

**Comment by jcw931** [comment]
I updated both our API and Swaggerhub. I hope it fixes the current issue

**Comment by JacobAMason** [comment]
Close, but not quite. The API claims that the return type is an Array of Inventory objects, but the implementation is an object with an attribute called "inventory" that has an Array of Inventory objects as its value.

**Comment by jcw931** [comment]
I figured out what you were saying. I was overlooking the array line. I changed the ref but not the array part. It should match now

**Comment by JacobAMason** [comment]
lgtm
