### ISSUE TITLE
Some cruises depart on invalid date

### ISSUE THREAD

**Issue by BlakeHolifield** [ejzavala00/Carnivore-Cruise-Lines#9]
A few cruises (Jurassic Park) leave on 11/31. November only has 30 days, so it returns an Invalid Date in JavaScript. Please update the departure dates to 11/30 or 12/01. 

Can be seen in this response:
http://35.196.221.242/inventory/location/Atlanta,%20GA

**Comment by jcw931** [comment]
Sorry about that. Brandon said he forgot how a calendar works. We will get that to ya ASAP

**Comment by jcw931** [comment]
Should be good to go

**Comment by BlakeHolifield** [comment]
I had a good chuckle when I figured out what was actually happening. Working just fine now. Thanks!
